feat: add v-update-sys-hestia-git script to build and install HestiaCP from GitHub repositories

diff --git a/bin/v-update-sys-hestia-git b/bin/v-update-sys-hestia-git
--- a/bin/v-update-sys-hestia-git
+++ b/bin/v-update-sys-hestia-git
@@ -24,19 +24,17 @@ source_conf "$HESTIA/conf/hestia.conf"
 # Perform verification if read-only mode is enabled
 check_hestia_demo_mode
 
-# Detect and install Node.js if necessary
-if [ -z $(which "node") ]; then
-	echo "Installing Node.js $node_v"
-	apt="/etc/apt/sources.list.d"
-	node_v="20"
-	if [ $(uname -m) = "x86_64" ]; then
-		ARCH=amd64
-	elif [ $(uname -m) = "aarch64" ]; then
-		ARCH=arm64
+# Detect and install Node.js and npm if necessary
+if [ -z "$(which "node")" ] || [ -z "$(which "npm")" ]; then
+	echo "Installing Node.js and npm..."
+	if [ -z "$(which "node")" ]; then
+		curl -fsSL https://deb.nodesource.com/setup_24.x | bash - > /dev/null 2>&1
+		apt-get -qq update > /dev/null 2>&1
+		apt-get -qq install -y nodejs > /dev/null 2>&1
 	fi
-	echo "deb [arch=$ARCH signed-by=/usr/share/keyrings/nodejs.gpg] https://deb.nodesource.com/node_$node_v.x nodistro main" > $apt/nodejs.list
-	curl -s https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodejs.gpg > /dev/null 2>&1
-	apt-get -qq install nodejs -y
+	if [ -z "$(which "npm")" ]; then
+		apt-get -qq install -y npm > /dev/null 2>&1
+	fi
 fi
 
 # Define download function
@@ -47,38 +45,47 @@ download_file() {
 
 	# Default destination is the current working directory
 	local dstopt=""
+	local is_archive="false"
+	local filename="${url##*/}"
 
 	if [ ! -z "$(echo "$url" | grep -E "\.(gz|gzip|bz2|zip|xz)$")" ]; then
-		# When an archive file is downloaded it will be first saved localy
+		# When an archive file is downloaded it will be first saved locally
 		dstopt="--directory-prefix=$ARCHIVE_DIR"
-		local is_archive="true"
-		local filename="${url##*/}"
+		is_archive="true"
 		if [ -z "$filename" ]; then
 			echo >&2 "[!] No filename was found in url, exiting ($url)"
 			exit 1
 		fi
 		if [ ! -z "$force" ] && [ -f "$ARCHIVE_DIR/$filename" ]; then
-			rm -f $ARCHIVE_DIR/$filename
+			rm -f "$ARCHIVE_DIR/$filename"
 		fi
 	elif [ ! -z "$destination" ]; then
 		# Plain files will be written to specified location
 		dstopt="-O $destination"
 	fi
+
 	# check for corrupted archive
 	if [ -f "$ARCHIVE_DIR/$filename" ] && [ "$is_archive" = "true" ]; then
 		tar -tzf "$ARCHIVE_DIR/$filename" > /dev/null 2>&1
 		if [ $? -ne 0 ]; then
 			echo >&2 "[!] Archive $ARCHIVE_DIR/$filename is corrupted, redownloading"
-			rm -f $ARCHIVE_DIR/$filename
+			rm -f "$ARCHIVE_DIR/$filename"
 		fi
 	fi
 
-	if [ ! -f "$ARCHIVE_DIR/$filename" ]; then
-		[ "$HESTIA_DEBUG" ] && echo >&2 DEBUG: wget $url -q $dstopt --show-progress --progress=bar:force --limit-rate=3m
-		wget $url -q $dstopt --show-progress --progress=bar:force --limit-rate=3m
+	if [ "$is_archive" = "true" ] && [ ! -f "$ARCHIVE_DIR/$filename" ]; then
+		[ "$HESTIA_DEBUG" ] && echo >&2 DEBUG: wget "$url" -q $dstopt --show-progress --progress=bar:force --limit-rate=3m
+		wget "$url" -q $dstopt --show-progress --progress=bar:force --limit-rate=3m
 		if [ $? -ne 0 ]; then
 			echo >&2 "[!] Archive $ARCHIVE_DIR/$filename is corrupted and exit script"
-			rm -f $ARCHIVE_DIR/$filename
+			rm -f "$ARCHIVE_DIR/$filename"
+			exit 1
+		fi
+	elif [ "$is_archive" = "false" ]; then
+		[ "$HESTIA_DEBUG" ] && echo >&2 DEBUG: wget "$url" -q $dstopt
+		wget "$url" -q $dstopt
+		if [ $? -ne 0 ]; then
+			echo >&2 "[!] Download failed for $url"
 			exit 1
 		fi
 	fi
@@ -96,7 +103,9 @@ get_branch_file() {
 	local filename=$1
 	local destination=$2
 	[ "$HESTIA_DEBUG" ] && echo >&2 DEBUG: Get branch file "$filename" to "$destination"
-	if [ "$use_src_folder" == 'true' ]; then
+	if [ -f "$BUILD_DIR/hestiacp-$branch_dash/$filename" ]; then
+		cp -f "$BUILD_DIR/hestiacp-$branch_dash/$filename" "$destination"
+	elif [ "$use_src_folder" == 'true' ]; then
 		if [ -z "$destination" ]; then
 			[ "$HESTIA_DEBUG" ] && echo >&2 DEBUG: cp -f "$SRC_DIR/$filename" ./
 			cp -f "$SRC_DIR/$filename" ./
